import { Feedback } from "./db";

export const mockFeedback: Feedback[] = [
  {
    id: 1,
    type: "academic",
    text: "The new math curriculum is very engaging and well-structured. Students are showing great progress.",
    date: new Date(2024, 2, 1).toISOString(),
    status: "Reviewed",
    userId: 1,
    userName: "John Smith",
  },
  {
    id: 2,
    type: "facilities",
    text: "The library needs more study spaces for group work. Current setup is not sufficient for collaborative projects.",
    date: new Date(2024, 2, 5).toISOString(),
    status: "Pending",
    userId: 2,
    userName: "Sarah Johnson",
  },
  {
    id: 3,
    type: "general",
    text: "School events are well organized, but it would be great to have more advance notice for upcoming activities.",
    date: new Date(2024, 2, 10).toISOString(),
    status: "Pending",
    userId: 3,
    userName: "Michael Brown",
  },
  {
    id: 4,
    type: "academic",
    text: "The science lab equipment needs updating. Some microscopes are not functioning properly.",
    date: new Date(2024, 2, 15).toISOString(),
    status: "Reviewed",
    userId: 4,
    userName: "Emily Davis",
  },
  {
    id: 5,
    type: "facilities",
    text: "The cafeteria food quality has improved significantly this semester. Keep up the good work!",
    date: new Date(2024, 2, 20).toISOString(),
    status: "Pending",
    userId: 5,
    userName: "David Wilson",
  },
  {
    id: 6,
    type: "academic",
    text: "The new online learning platform is user-friendly and helps students stay organized.",
    date: new Date(2024, 2, 25).toISOString(),
    status: "Reviewed",
    userId: 6,
    userName: "Lisa Anderson",
  },
  {
    id: 7,
    type: "facilities",
    text: "The sports facilities need maintenance. The basketball court surface is becoming uneven.",
    date: new Date(2024, 3, 1).toISOString(),
    status: "Pending",
    userId: 7,
    userName: "Robert Taylor",
  },
  {
    id: 8,
    type: "general",
    text: "Communication between teachers and parents could be improved through the school portal.",
    date: new Date(2024, 3, 5).toISOString(),
    status: "Pending",
    userId: 8,
    userName: "Jennifer White",
  },
  {
    id: 9,
    type: "academic",
    text: "The new language program is excellent. Students are making great progress in Spanish.",
    date: new Date(2024, 3, 10).toISOString(),
    status: "Reviewed",
    userId: 9,
    userName: "Thomas Lee",
  },
  {
    id: 10,
    type: "facilities",
    text: "The school's Wi-Fi coverage in some classrooms is inconsistent and needs improvement.",
    date: new Date(2024, 3, 15).toISOString(),
    status: "Pending",
    userId: 10,
    userName: "Maria Garcia",
  },
  {
    id: 11,
    type: "general",
    text: "I'd like to suggest adding more extracurricular activities focused on technology and coding. Many students have shown interest in these areas.",
    date: new Date(2024, 3, 18).toISOString(),
    status: "Pending",
    userId: 12,
    userName: "James Wilson",
  },
  {
    id: 12,
    type: "academic",
    text: "The reading program has been excellent for my child. I've seen significant improvement in their comprehension skills over the past few months.",
    date: new Date(2024, 3, 20).toISOString(),
    status: "Pending",
    userId: 15,
    userName: "Anna Martinez",
  },
  {
    id: 13,
    type: "facilities",
    text: "The playground equipment needs inspection. Some of the swings appear to be worn out and could pose safety concerns.",
    date: new Date(2024, 3, 22).toISOString(),
    status: "Pending",
    userId: 18,
    userName: "Richard Thompson",
  },
  {
    id: 14,
    type: "general",
    text: "Thank you for organizing the science fair last month. It was well-executed and students were very engaged with the projects.",
    date: new Date(2024, 3, 25).toISOString(),
    status: "Reviewed",
    userId: 14,
    userName: "Karen Adams",
  },
  {
    id: 15,
    type: "academic",
    text: "Could we have more resources for students who are ahead of the curriculum? My child finishes assignments quickly and could benefit from additional challenges.",
    date: new Date(2024, 3, 27).toISOString(),
    status: "Pending",
    userId: 16,
    userName: "Jason Miller",
  },
  {
    id: 16,
    type: "facilities",
    text: "The art room needs better ventilation. When all students are using paints, the room gets stuffy very quickly.",
    date: new Date(2024, 3, 29).toISOString(),
    status: "Pending",
    userId: 11,
    userName: "Patricia Clark",
  },
  {
    id: 17,
    type: "general",
    text: "The new drop-off and pick-up procedure has significantly improved traffic flow. Much safer for students now.",
    date: new Date(2024, 4, 2).toISOString(),
    status: "Reviewed",
    userId: 19,
    userName: "Daniel Wilson",
  },
  {
    id: 18,
    type: "academic",
    text: "I'm concerned about the homework load for 4th graders. It seems excessive and is cutting into family time and other activities.",
    date: new Date(2024, 4, 5).toISOString(),
    status: "Pending",
    userId: 17,
    userName: "Susan Parker",
  },
  {
    id: 19,
    type: "facilities",
    text: "Could we look into more environmentally friendly options for the cafeteria? The amount of plastic waste generated is concerning.",
    date: new Date(2024, 4, 8).toISOString(),
    status: "Pending",
    userId: 13,
    userName: "Kevin Wright",
  },
  {
    id: 20,
    type: "general",
    text: "The recent parent-teacher conferences were well organized. The online scheduling system made it very convenient.",
    date: new Date(2024, 4, 10).toISOString(),
    status: "Pending",
    userId: 20,
    userName: "Elizabeth Turner",
  },
];

export interface Form {
  id: string;
  title: string;
  description: string;
  category: "academic" | "administrative" | "permission" | "health" | "other";
  downloadUrl: string;
  createdAt: string;
  updatedAt: string;
  editable?: boolean;
}

export const mockForms: Form[] = [
  {
    id: "1",
    title: "Student Registration Form",
    description: "New student registration and enrollment form",
    category: "administrative",
    downloadUrl: "#",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
    editable: true,
  },
  {
    id: "2",
    title: "Field Trip Permission Slip",
    description: "Permission form for upcoming school field trips",
    category: "permission",
    downloadUrl: "#",
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
    editable: true,
  },
  {
    id: "3",
    title: "Medical Information Form",
    description: "Student health and medical information update form",
    category: "health",
    downloadUrl: "#",
    createdAt: "2024-02-01",
    updatedAt: "2024-02-01",
    editable: true,
  },
  {
    id: "4",
    title: "Parent-Teacher Conference Request",
    description: "Form to request a meeting with teachers",
    category: "academic",
    downloadUrl: "#",
    createdAt: "2024-02-15",
    updatedAt: "2024-02-15",
    editable: true,
  },
  {
    id: "5",
    title: "After-School Program Registration",
    description: "Registration form for after-school activities",
    category: "academic",
    downloadUrl: "#",
    createdAt: "2024-03-01",
    updatedAt: "2024-03-01",
    editable: true,
  },
  {
    id: "6",
    title: "School Lunch Program Application",
    description: "Application for the school lunch program",
    category: "administrative",
    downloadUrl: "#",
    createdAt: "2024-03-15",
    updatedAt: "2024-03-15",
    editable: true,
  },
  {
    id: "7",
    title: "Technology Usage Agreement",
    description: "Student technology usage and responsibility agreement",
    category: "administrative",
    downloadUrl: "#",
    createdAt: "2024-04-01",
    updatedAt: "2024-04-01",
    editable: true,
  },
  {
    id: "8",
    title: "Emergency Contact Update",
    description: "Form to update emergency contact information",
    category: "health",
    downloadUrl: "#",
    createdAt: "2024-04-15",
    updatedAt: "2024-04-15",
    editable: true,
  },
  {
    id: "9",
    title: "Teacher Observation Form",
    description: "Form for recording classroom observations",
    category: "academic",
    downloadUrl: "#",
    createdAt: "2024-05-01",
    updatedAt: "2024-05-01",
    editable: true,
  },
  {
    id: "10",
    title: "Library Book Request Form",
    description: "Form to request new books for the library",
    category: "administrative",
    downloadUrl: "#",
    createdAt: "2024-05-15",
    updatedAt: "2024-05-15",
    editable: true,
  },
  {
    id: "11",
    title: "Curriculum Planning Template",
    description: "Template for planning academic curriculum",
    category: "academic",
    downloadUrl: "#",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-01",
    editable: true,
  },
  {
    id: "12",
    title: "Library Card Application",
    description: "Application form for school library card",
    category: "administrative",
    downloadUrl: "#",
    createdAt: "2024-06-15",
    updatedAt: "2024-06-15",
    editable: true,
  },
  {
    id: "13",
    title: "Book Acquisition Form",
    description: "Form for requesting new book purchases",
    category: "administrative",
    downloadUrl: "#",
    createdAt: "2024-07-01",
    updatedAt: "2024-07-01",
    editable: true,
  },
  {
    id: "14",
    title: "Book Removal Request",
    description: "Form for requesting removal of damaged or outdated books",
    category: "administrative",
    downloadUrl: "#",
    createdAt: "2024-07-15",
    updatedAt: "2024-07-15",
    editable: true,
  },
  {
    id: "15",
    title: "Library Inventory Form",
    description: "Form for conducting library inventory",
    category: "administrative",
    downloadUrl: "#",
    createdAt: "2024-08-01",
    updatedAt: "2024-08-01",
    editable: true,
  },
];
